#include "cinder/cinder.h"

class OutlineParams {
		float NUI_SKELETON_POSITION_HIP_CENTER_force;
		float NUI_SKELETON_POSITION_SPINE_force;
		float NUI_SKELETON_POSITION_SHOULDER_CENTER_force;
		float NUI_SKELETON_POSITION_HEAD_force;
		float NUI_SKELETON_POSITION_SHOULDER_LEFT_force;
		float NUI_SKELETON_POSITION_ELBOW_LEFT_force;
		float NUI_SKELETON_POSITION_WRIST_LEFT_force;
		float NUI_SKELETON_POSITION_HAND_LEFT_force;
		float NUI_SKELETON_POSITION_SHOULDER_RIGHT_force;
		float NUI_SKELETON_POSITION_ELBOW_RIGHT_force;
		float NUI_SKELETON_POSITION_WRIST_RIGHT_force;
		float NUI_SKELETON_POSITION_HAND_RIGHT_force;
		float NUI_SKELETON_POSITION_HIP_LEFT_force;
		float NUI_SKELETON_POSITION_KNEE_LEFT_force;
		float NUI_SKELETON_POSITION_ANKLE_LEFT_force;
		float NUI_SKELETON_POSITION_FOOT_LEFT_force;
		float NUI_SKELETON_POSITION_HIP_RIGHT_force;
		float NUI_SKELETON_POSITION_KNEE_RIGHT_force;
		float NUI_SKELETON_POSITION_ANKLE_RIGHT_force;
		float NUI_SKELETON_POSITION_FOOT_RIGHT_force;



		float NUI_SKELETON_POSITION_HIP_CENTER_distance;
		float NUI_SKELETON_POSITION_SPINE_distance;
		float NUI_SKELETON_POSITION_SHOULDER_CENTER_distance;
		float NUI_SKELETON_POSITION_HEAD_distance;
		float NUI_SKELETON_POSITION_SHOULDER_LEFT_distance;
		float NUI_SKELETON_POSITION_ELBOW_LEFT_distance;
		float NUI_SKELETON_POSITION_WRIST_LEFT_distance;
		float NUI_SKELETON_POSITION_HAND_LEFT_distance;
		float NUI_SKELETON_POSITION_SHOULDER_RIGHT_distance;
		float NUI_SKELETON_POSITION_ELBOW_RIGHT_distance;
		float NUI_SKELETON_POSITION_WRIST_RIGHT_distance;
		float NUI_SKELETON_POSITION_HAND_RIGHT_distance;
		float NUI_SKELETON_POSITION_HIP_LEFT_distance;
		float NUI_SKELETON_POSITION_KNEE_LEFT_distance;
		float NUI_SKELETON_POSITION_ANKLE_LEFT_distance;
		float NUI_SKELETON_POSITION_FOOT_LEFT_distance;
		float NUI_SKELETON_POSITION_HIP_RIGHT_distance;
		float NUI_SKELETON_POSITION_KNEE_RIGHT_distance;
		float NUI_SKELETON_POSITION_ANKLE_RIGHT_distance;
		float NUI_SKELETON_POSITION_FOOT_RIGHT_distance;

}





